### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by sueCalystegia00** [ExpectBonus/doko-yahoo#9]
みんなでDockerを弄ってVue.jsとDjangoのさいきょうかんきょうをつくろう

**Comment by sho-yoshikawa** [comment]
Dockerでvue

- docker-compose.yml
```
version: '3'
services:
  vue:
    container_name: vue
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "../:/var/www/html"
    tty: true
```

- Dockerfile
```
FROM node:17-alpine3.14

WORKDIR /var/www/html

RUN apk update && \
    npm install -g npm && \
    npm install -g @vue/cli

EXPOSE 8080
ENV HOST 0.0.0.0
```

- docker composeする
```
docker-compose -f .vue_v3_docker/docker-compose.yml up -d
```

- コンテナに入る
```
docker-compose -f .vue_v3_docker/docker-compose.yml exec vue sh
``` 

- プロジェクトを作る
```
 vue create first-app
cd first-app
npm run serve
```
localhost:
8080
-
